services:
#    oc_user.example:
#        class: OCUserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  OC\UserBundle\DataFixtures\LoadUser:
      tags: [doctrine.fixture.orm]