services:
#    oc_platform.example:
#        class: OC\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  oc_platform.antispam:
    class: OC\PlatformBundle\Antispam\OCAntispam
    arguments:
        - "@mailer"
        - %locale%
        - 5
  OC\PlatformBundle\DataFixtures\ORM\LoadCategory:
      tags: [doctrine.fixture.orm]
  OC\PlatformBundle\DataFixtures\ORM\LoadSkill:
      tags: [doctrine.fixture.orm]
  OC\PlatformBundle\DataFixtures\ORM\LoadAdvert:
      tags: [doctrine.fixture.orm]
  oc_platform.email.application_mailer:
    class: OCPlatformBundle\Email\ApplicationMailer
    arguments:
      - "@mailer"
  oc_platform.doctrine_listener.application_creation:
    class: OCPlatformBundle\DoctrineListener\ApplicationCreationListener
    arguments:
      - "@oc_platform.email.application_mailer"
    tags:
      - { name: doctrine.event_listener, event: postPersist }
  oc_platform.purger.advert:
    class: OCPlatformBundle\PurgeAdvert\OCPurgerAdvert
    arguments: ['@doctrine.orm.entity_manager']
