OC\PlatformBundle\Entity\Advert:
    type: entity
    table: null
    repositoryClass: OC\PlatformBundle\Repository\AdvertRepository
    lifecycleCallbacks:
        preUpdate: [preUpdate]
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        author:
            type: string
            length: 255
        date:
            type: datetime
        content:
            type: text
        published:
            type: boolean
        updateAt:
            type: datetime
            nullable: true
        nbApplications:
            type: integer
        slug:
            type: string
            length: 256
            unique: true
            gedmo:
              slug:
                fields:
                  - title
    oneToOne:
        image:
          targetEntity: OC\PlatformBundle\Entity\Image
          joinColumn:
            name: image_id
            referencedColumnName: id
          cascade: [persist, remove]
    manyToMany:
      categories:
        targetEntity: OC\PlatformBundle\Entity\Category
        joinTable:
          name: advert_category
          joinColumns:
            adver_id:
              referencedColumnName: id
          inverseJoinColumns:
            category_id:
              referencedColumnName: id
        cascade: [persist]
    oneToMany:
      applications:
        targetEntity: OC\PlatformBundle\Entity\Application
        mappedBy: advert
    lifecycleCallbacks: {  }
