OC\PlatformBundle\Entity\Advert:
    type: entity
    table: null
    repositoryClass: OC\PlatformBundle\Repository\AdvertRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        author:
            type: string
            length: 255
        date:
            type: datetime
        content:
            type: text
    lifecycleCallbacks: {  }
