OC\PlatformBundle\Entity\Application:
    type: entity
    table: null
    repositoryClass: OC\PlatformBundle\Repository\ApplicationRepository
    lifecycleCallbacks:
            prePersist: [increase, saveDate]
            preRemove: [decrease]
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        author:
            type: string
            length: 255
        content:
            type: text
        date:
            type: datetime
            nullable: true
        ipAddress:
            type: string
            length: 24
            nullable: true
    manyToOne:
        advert:
            targetEntity: OC\PlatformBundle\Entity\Advert
            inversedBy: applications
            joinColumn:
                name: advert_id
                referencedColumnName: id
                nullable: false

    lifecycleCallbacks: {  }
