OC\PlatformBundle\Entity\Image:
    type: entity
    table: null
    repositoryClass: OC\PlatformBundle\Repository\ImageRepository
    lifecycleCallbacks:
            prePersist: [preUpload]
            preUpdate: [preUpload]
            postPersist: [upload]
            postUpdate: [upload]
            postRemove: [removeUpload]
            preRemove: [preRemoveUpload]
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        url:
            type: string
            length: 255
        alt:
            type: string
            length: 255
    lifecycleCallbacks: {  }
