<?php

namespace OC\PlatformBundle\Repository;


/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends \Doctrine\ORM\EntityRepository {

  public function getApplicationsWithAdvert($limit) {

    $qb = $this->createQueryBuilder('a');

    $qb->innerJoin('a.advert', 'adv')
      ->addSelect('adv');

    $qb->setMaxResults($limit);

    return $qb
      ->getQuery()
      ->getResult();
  }

  public function isFlood($ip, $time) {
    $qb = $this->createQueryBuilder('a')
      ->select('COUNT(a)')
      ->where('a.ipAddress = :ip')
      ->setParameter('ip', $ip)
      ->andWhere('a.date >= :date')
      ->setParameter('date', new \Datetime('-' . $time . 'seconds'));
    return (bool) $qb->getQuery()->getSingleScalarResult();
  }
}
